#-----------------------------------------------------------------------------
# Makefile for RISCV 32 bit integer base assembly tests and benchmarks for
# use with the Sodor processors.
#----------------------------------------------------------------------------


install: 
	make -C riscv-isa install;
	make -C riscv-benchmarks install
