/* MTI_DPI */

/*
 * Copyright 2002-2010 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux_x86_64'
 */
#ifndef INCLUDED_DISASM_MODELSIM
#define INCLUDED_DISASM_MODELSIM

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C"
#else
#define DPI_LINK_DECL
#endif

#include "svdpi.h"


DPI_LINK_DECL DPI_DLLESPEC
void
riscv_disasm(
  const svBitVecVal* insn,
  svBitVecVal* dasm,
  svBitVecVal* minidasm);

#endif
